os: osx
language: node_js
node_js:
  - "4.2.3"
services:
  - mongodb
before_script:
  - brew update
  - brew install mongodb
  - brew services start mongodb
  - npm install gulp
  - gulp
  - gulp webpack:test
  - npm install karma
  - npm install jasmine
  - jasmine init
  - npm install phantomjs-prebuilt
  - npm install karma-phantomjs-launcher
script:
  - sleep 15
  - npm test
  - karma start
