language: node_js
node_js:
  - "4.2.3"
env:
  - CXX=g++-4.8
script:
  - TGT_DIR=/opt/opencl-headers/include/CL
  - mkdir -p $TGT_DIR && cd $TGT_DIR
  - wget https://github.com/KhronosGroup/OpenCL-Headers/blob/master/{opencl,cl_platform,cl,cl_ext,cl_gl,cl_gl_ext}.h
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - opencl-headers
      - nvidia-opencl-dev
